FROM python:3.12-slim
RUN apt-get update && apt-get install -y build-essential
WORKDIR /code # set the working directory

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install crewai==0.67.1