apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kalygo-crewai-api-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/kalygo-436411/kalygo-crewai-api/kalygo-crewai-api
          env:
            - name: AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: AUTH_SECRET_KEY
                  key: latest
            - name: AUTH_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: AUTH_ALGORITHM
                  key: latest

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: OPENAI_API_KEY
                  key: latest
            
            - name: AWS_REGION 
              valueFrom:
                secretKeyRef:
                  name: AWS_REGION
                  key: latest

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: AWS_ACCESS_KEY_ID
                  key: latest

            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: AWS_SECRET_KEY
                  key: latest
          ports:
            - containerPort: 8080